<?php
@session_start();
$_SESSION['creator']="Dwi Zuna";
$_SESSION['profile']="<p>Praesent vehicula iaculis sagittis. Morbi vel risus justo. Ut eget sollicitudin quam, nec lobortis tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla hendrerit turpis id nibh consectetur, sed varius elit vestibulum. Nullam dignissim porttitor luctus. Proin lobortis, dui imperdiet accumsan pellentesque, nibh nisi convallis dui, sed aliquam dolor enim ut turpis. Proin gravida nisi sit amet lacinia iaculis. Ut scelerisque purus ipsum, id luctus odio tincidunt non. Nullam quis volutpat turpis, non aliquam est. Proin vehicula, eros ut porttitor fermentum, est lectus luctus ante, et vestibulum nunc massa a risus. Aliquam in arcu at mauris maximus finibus vel ut ipsum. Pellentesque molestie molestie neque. Nulla tristique sapien id purus posuere, nec viverra nunc imperdiet.</p>";
$_SESSION['judul']="ForecastingKu";
$_SESSION['versi']="1.0 rc";
$_SESSION['beranda']="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque aliquet consectetur est. Praesent risus metus, molestie nec libero id, dapibus varius tortor. In sed neque nec lorem euismod consectetur. Mauris vulputate neque quam, ut mattis est aliquet vel. Fusce pharetra a eros quis consectetur. Nam ultricies mi quam, in efficitur sapien convallis vitae. Morbi semper, enim ut cursus eleifend, mi tellus hendrerit velit, non condimentum enim massa eu ante. Quisque sed dui nec nisi condimentum blandit vel eget ante. Donec in finibus erat, et tempor justo. Aenean sed nisi eget augue ultricies feugiat quis in elit. Vivamus semper placerat pellentesque. Integer convallis ipsum et mi finibus, et tincidunt lorem ultricies. Quisque eu lacinia lectus.</p>

<p>Praesent vehicula iaculis sagittis. Morbi vel risus justo. Ut eget sollicitudin quam, nec lobortis tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla hendrerit turpis id nibh consectetur, sed varius elit vestibulum. Nullam dignissim porttitor luctus. Proin lobortis, dui imperdiet accumsan pellentesque, nibh nisi convallis dui, sed aliquam dolor enim ut turpis. Proin gravida nisi sit amet lacinia iaculis. Ut scelerisque purus ipsum, id luctus odio tincidunt non. Nullam quis volutpat turpis, non aliquam est. Proin vehicula, eros ut porttitor fermentum, est lectus luctus ante, et vestibulum nunc massa a risus. Aliquam in arcu at mauris maximus finibus vel ut ipsum. Pellentesque molestie molestie neque. Nulla tristique sapien id purus posuere, nec viverra nunc imperdiet.</p>

<p>Ut purus lacus, vulputate et hendrerit elementum, consequat id justo. Duis consequat, ipsum et dictum iaculis, mi tellus auctor turpis, a tempor arcu quam nec nisi. Nullam sed aliquet nisl, eu ornare sem. Nullam molestie lectus tincidunt, egestas massa a, varius libero. Sed eget risus ante. Proin nibh velit, semper cursus nunc consequat, varius tristique enim. Donec bibendum quis quam sed vehicula. Ut sed interdum enim. Cras consectetur, tellus nec tempor rutrum, orci leo placerat purus, sed suscipit massa purus eu ante.</p>";
?>